#pragma once

#include "utils/internal/thread_annotation.hpp"

#define DUCKDB_GUARDED_BY(x)    DUCKDB_THREAD_ANNOTATION_ATTRIBUTE(guarded_by(x))
#define DUCKDB_PT_GUARDED_BY(x) DUCKDB_THREAD_ANNOTATION_ATTRIBUTE(pt_guarded_by(x))

#define DUCKDB_REQUIRES(...)        DUCKDB_THREAD_ANNOTATION_ATTRIBUTE(requires_capability(__VA_ARGS__))
#define DUCKDB_REQUIRES_SHARED(...) DUCKDB_THREAD_ANNOTATION_ATTRIBUTE(requires_shared_capability(__VA_ARGS__))

#define DUCKDB_ACQUIRE(...)        DUCKDB_THREAD_ANNOTATION_ATTRIBUTE(acquire_capability(__VA_ARGS__))
#define DUCKDB_ACQUIRE_SHARED(...) DUCKDB_THREAD_ANNOTATION_ATTRIBUTE(acquire_shared_capability(__VA_ARGS__))

#define DUCKDB_ACQUIRED_BEFORE(...) DUCKDB_THREAD_ANNOTATION_ATTRIBUTE(acquired_before(__VA_ARGS__))
#define DUCKDB_ACQUIRED_AFTER(...)  DUCKDB_THREAD_ANNOTATION_ATTRIBUTE(acquired_after(__VA_ARGS__))

#define DUCKDB_RELEASE(...)         DUCKDB_THREAD_ANNOTATION_ATTRIBUTE(release_capability(__VA_ARGS__))
#define DUCKDB_RELEASE_SHARED(...)  DUCKDB_THREAD_ANNOTATION_ATTRIBUTE(release_shared_capability(__VA_ARGS__))
#define DUCKDB_RELEASE_GENERIC(...) DUCKDB_THREAD_ANNOTATION_ATTRIBUTE(release_generic_capability(__VA_ARGS__))

#define DUCKDB_EXCLUDES(...)             DUCKDB_THREAD_ANNOTATION_ATTRIBUTE(locks_excluded(__VA_ARGS__))
#define DUCKDB_NO_THREAD_SAFETY_ANALYSIS DUCKDB_THREAD_ANNOTATION_ATTRIBUTE(no_thread_safety_analysis)
#define DUCKDB_RETURN_CAPABILITY(x)      DUCKDB_THREAD_ANNOTATION_ATTRIBUTE(lock_returned(x))

#define DUCKDB_TRY_ACQUIRE(...)        DUCKDB_THREAD_ANNOTATION_ATTRIBUTE(try_acquire_capability(__VA_ARGS__))
#define DUCKDB_TRY_ACQUIRE_SHARED(...) DUCKDB_THREAD_ANNOTATION_ATTRIBUTE(try_acquire_shared_capability(__VA_ARGS__))

#define DUCKDB_ASSERT_CAPABILITY(x)        DUCKDB_THREAD_ANNOTATION_ATTRIBUTE(assert_capability(x))
#define DUCKDB_ASSERT_SHARED_CAPABILITY(x) DUCKDB_THREAD_ANNOTATION_ATTRIBUTE(assert_shared_capability(x))
