syntax = "proto3";

package duckdb.distributed;

import "storage.proto";

enum ClientRole {
  CLIENT_ROLE_UNSPECIFIED = 0;
  CLIENT_ROLE_READ_ONLY = 1;
  CLIENT_ROLE_READ_WRITE = 2;
}

// Register a Duckherder attachment with the control node.
message RegisterClientRequest {
  ClientRole role = 1;
  StorageConfig storage_config = 2;
}

message RegisterClientResponse {
  string client_id = 1;
}

message UnregisterClientRequest {}

message UnregisterClientResponse {}

message ClientHeartbeatRequest {}

message ClientHeartbeatResponse {}

message LoadExtensionRequest {
  string extension_name = 1;
  string repository = 2;
  string version = 3;
}

message LoadExtensionResponse {}
